name: "setup-js-deps"
description: "Clone repo and run yarn install to make app ready to use"
author: "Nick Strayer"
# inputs:
#   working-directory:
#     description: 'Using the working-directory keyword, you can specify the working directory of where "pkg_deps" command searches for dependencies in the "DESCRIPTION" file.'
#     default: "./inst/ui-editor-react"
#   cache:
#     description: 'A boolean value indicating whether packages should be cached from one to the other'
#     required: true
#     default: true
#   cache-version:
#     description: 'The version of the cache, change this from the default (1) to start over with a fresh cache. Ignored if cache: false'
#     required: true
#     default: 1
#   extra-packages:
#     description: 'Any extra packages to install outside of the packages listed in the dependencies'
#   needs:
#     description: 'Any extra Config/Needs fields which need to be included when installing dependencies'
#   packages:
#     description: 'Which package(s) to install.'
#     default: 'deps::., any::sessioninfo'
#   pak-version:
#     description: 'Which pak version to use. Possible values are "stable", "rc" and "devel".'
#     default: 'stable'
#   dependencies:
#     description: 'Types of dependencies to install. Must be an R expression in single quotes.'
#     default: '"all"'
runs:
  using: "composite"
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      working-directory: ./inst/ui-editor-react
      run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      shell: bash

    - uses: actions/cache@v3
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('inst/ui-editor-react/yarn.lock')  }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - uses: actions/setup-node@v3
      with:
        node-version: "16.x"

    - name: Install dependencies
      working-directory: ./inst/ui-editor-react
      run: yarn
      shell: bash
