import type { NodePath } from "ui-node-definitions/src/NodePath";
import type { ShinyUiNode } from "ui-node-definitions/src/ShinyUiNode";
import { collapseText } from "util-functions/src/strings";

import type { RootState } from "../state/store";

/**
 *
 * @param code Serialized code to be wrapped in code chunks
 * @param singleOrMultiline Whether to use single or multiline code chunks
 * @returns Markdown code chunk
 */
function generateCodeChunk(
  code: string,
  singleOrMultiline: "single" | "multi" = "multi"
) {
  const delimeter = singleOrMultiline === "single" ? "`" : "\n```\n";
  return `${delimeter}${code}${delimeter}`;
}

function singleLineCodeChunk(code: string) {
  return generateCodeChunk(code, "single");
}
function multiLineCodeChunk(code: string) {
  return generateCodeChunk(code, "multi");
}

/**
 *
 * @param appState Main app state when error occured
 * @returns A string that summarized salient state information for github issue
 */
export function generateSerializedStateForError(appState: RootState) {
  switch (appState.app_info.mode) {
    case "MAIN": {
      const uiTree = JSON.stringify(appState.app_info.ui_tree, null, 2);
      const currentSelection =
        (appState.selected_path ?? []).join(" > ") ?? "null";

      return collapseText(
        `## Ui-Tree at error:\n${multiLineCodeChunk(uiTree)}`,
        `__Selection path:__ ${singleLineCodeChunk(currentSelection)}`
      );
    }
    case "TEMPLATE_CHOOSER": {
      const templateChooserOptions = JSON.stringify(
        appState.app_info.options,
        null,
        2
      );
      return collapseText(
        `## Template chooser options at error:`,
        `${multiLineCodeChunk(templateChooserOptions)}`
      );
    }
    default: {
      const otherAppState = JSON.stringify(appState.app_info, null, 2);

      return `## App state at error:\n${multiLineCodeChunk(otherAppState)}`;
    }
  }
}

/**
 *
 * @param info Information about error to be encoded in github issue link with properties:
 * - `node`: The node being rendered when error occured
 * - `path`: Path to node
 * - `app_state`: Main app state at time of error
 *
 * @returns URL that encodes info about error in github issue is links to
 */
export function generateUiNodeGithubErrorLink(info: {
  /** The node being rendered when error occured */
  node: ShinyUiNode;
  /** Path to node */
  path: NodePath;
  /** Main app state at time of error */
  app_state: RootState;
}) {
  const { node, path, app_state } = info;
  return generateGhIssueURL({
    title: `Error rendering ${node.id}`,
    body: collapseText(
      `This is what I was going when this error happened...\n`,
      generateSerializedStateForError(app_state),
      `__Path to node at error:__ \`${path.join(" > ")}\``
    ),
    labels: ["testing-labels", "ui-node-rendering"],
  });
}

/**
 *
 * @param info Information for prefilling github issue with properties:
 * - `title`: Prefilled title of issue
 * - `body`: Prefilled body of issue
 * - `labels`: List of labels to add to issue (in addition to `"autogenerated"`)
 * @returns URL that links to github issue with the given info prefilled
 */
export function generateGhIssueURL(info: {
  title: string;
  body: string;
  labels?: string[];
}) {
  const buildUrl = () => {
    const params = [
      `title=${encodeURIComponent(info.title)}`,
      `labels=${encodeURIComponent(["autogenerated"].join(","))}`,
      `body=${encodeURIComponent(info.body)}`,
    ].join("&");

    return `https://github.com/rstudio/shinyuieditor/issues/new?${params}`;
  };

  // Check if url text is longer than 5000 characters and replace it with message saying it's too long if it is
  const fullUrl = buildUrl();

  // Based on https://www.geeksforgeeks.org/maximum-length-of-a-url-in-different-browsers/ as of 2022-03-23
  const maxBodyTextChars = 65000;

  if (fullUrl.length > maxBodyTextChars) {
    info.body =
      "State of app during error was too large to encode in url. Please describe state of app when error occured as best you can! Thank you!";
    return buildUrl();
  }

  return fullUrl;
}
