#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running type-check..."
yarn type-check

echo "Building assets..."
yarn build

git add inst/*/build/ 
git add inst/*/out/ 
echo "All good! 👍"
