#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running type-check..."
yarn type-check

echo "Building assets..."
yarn prod

git add inst/*/build/ 
git add inst/*/media/build/ 
git add *.vsix

echo "All good! 👍"
