name: Javascript Tests
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/internals/setup-js

  unit-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inst/ui-editor-react
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/internals/setup-js
      - name: Run unit tests
        run: yarn test run

  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./inst/ui-editor-react
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/internals/setup-js

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, any::devtools, local::.
          needs: website

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: ./inst/ui-editor-react/playwright-report/
          retention-days: 30
