# Run javascript unit and playwright tests
name: Javascript Tests
on:
  push:
    branches: [main, dev]
    pull_request:
      branches: [main, dev]

concurrency:
  group: ci-tests-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test

      # Setup R so we can test R backend in playwright tests
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, any::devtools, local::.
          needs: website

      - name: Install Playwright Browsers
        working-directory: ./inst/editor
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./inst/editor
        run: yarn playwright

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: ./inst/editor/playwright-report/
