# Build and deploy the vscode extension to the marketplace when a tag is pushed
# to main branch
on:
  push:
    tags:
      - "v[0-9]*"

name: Deploy Extension
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/internals/setup-js
      - run: yarn prod
      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v1
      #   with:
      #     packagePath: ./inst/vscode-extension/
      #     yarn: true
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }}
      #     dryRun: ${{ github.ref_name == 'main' }}
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          packagePath: ./inst/vscode-extension/
          yarn: true
          pat: ${{ secrets.VSCE_PAT }}
          registryUrl: https://marketplace.visualstudio.com
          dryRun: ${{ github.ref_name == 'main' }}
